export type Code = "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "11" | "12"
export type Month =
	| "Січень"
	| "Лютий"
	| "Березень"
	| "Квітень"
	| "Травень"
	| "Червень"
	| "Липень"
	| "Серпень"
	| "Вересень"
	| "Жовтень"
	| "Листопад"
	| "Грудень"
export type Rank = "asc" | "desc"
export type DateString = `${number}.${number}.${number}`